import type { Metadata } from "next";
import Link from "next/link";
import { Roboto, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { House, Search, Menu } from "lucide-react";
import { Input } from "@/components/ui/input";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased text-sm bg-background`}
      >
        <header className="sticky top-0 z-20 flex items-center justify-between px-4 py-4 border-b md:px-22 border-border bg-background/80 backdrop-blur-lg">
          <div className="flex">
            <Link href="/">
              <Button
                size="icon"
                variant="outline"
                className="hidden mr-2 cursor-pointer md:inline-flex"
              >
                <House />
              </Button>
            </Link>

            <Input
              type="text"
              placeholder="Nhập sản phẩm cần tìm kiếm"
              className="w-40 rounded-r-none md:w-xs"
            />
            <Button
              variant="outline"
              size="icon"
              className="border-l-0 rounded-l-none"
            >
              <Search />
            </Button>
          </div>

          <NavigationMenu className="hidden md:block">
            <NavigationMenuList>
              <NavigationMenuItem>
                <NavigationMenuTrigger>Laptop mới</NavigationMenuTrigger>
                <NavigationMenuContent>
                  <NavigationMenuLink>Lenovo</NavigationMenuLink>
                  <NavigationMenuLink>Dell</NavigationMenuLink>
                  <NavigationMenuLink>HP</NavigationMenuLink>
                  <NavigationMenuLink>ASUS</NavigationMenuLink>
                  <NavigationMenuLink>Acer</NavigationMenuLink>
                  <NavigationMenuLink>Case đồng bộ Dell</NavigationMenuLink>
                </NavigationMenuContent>
              </NavigationMenuItem>

              <NavigationMenuItem>
                <NavigationMenuTrigger>Laptop cũ</NavigationMenuTrigger>
                <NavigationMenuContent>
                  <NavigationMenuLink>Lenovo</NavigationMenuLink>
                  <NavigationMenuLink>Dell</NavigationMenuLink>
                  <NavigationMenuLink>HP</NavigationMenuLink>
                  <NavigationMenuLink>ASUS</NavigationMenuLink>
                  <NavigationMenuLink>Acer</NavigationMenuLink>
                  <NavigationMenuLink>Case đồng bộ Dell</NavigationMenuLink>
                </NavigationMenuContent>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>

          <Button className="md:hidden" size="icon" variant="outline">
            <Menu />
          </Button>
        </header>

        {children}

        <footer className="px-4 py-6 mt-4 border-t md:px-22 border-border">
          this is the footer
        </footer>

        {/* Testing area */}
        {/* <div className="pl-8">
          <Select>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Theme" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="light">Light</SelectItem>
              <SelectItem value="dark">Dark</SelectItem>
              <SelectItem value="system">System</SelectItem>
            </SelectContent>
          </Select>
        </div> */}
      </body>
    </html>
  );
}
