import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { House, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased *:px-22 *:not-first:mt-4 text-sm bg-background`}
      >
        <header className="sticky top-0 z-20 flex items-center justify-between py-4 border-b border-border bg-background/80 backdrop-blur-lg">
          <div className="flex">
            <Button size="icon" variant="outline" className="mr-2">
              <House />
            </Button>

            <Input
              type="text"
              placeholder="Nhập sản phẩm cần tìm kiếm"
              className="rounded-r-none w-xs"
            />
            <Button
              variant="outline"
              size="icon"
              className="border-l-0 rounded-l-none"
            >
              <Search />
            </Button>
          </div>

          <NavigationMenu>
            <NavigationMenuList>
              <NavigationMenuItem className="relative">
                <NavigationMenuTrigger>Laptop mới</NavigationMenuTrigger>
                <NavigationMenuContent className="absolute right-0 w-auto select-none min-w-max">
                  <NavigationMenuLink className="w-auto">
                    Lenovo
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Dell
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">HP</NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    ASUS
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Acer
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Case đồng bộ Dell
                  </NavigationMenuLink>
                </NavigationMenuContent>
              </NavigationMenuItem>

              <NavigationMenuItem className="relative">
                <NavigationMenuTrigger>Laptop cũ</NavigationMenuTrigger>
                <NavigationMenuContent className="absolute right-0 w-auto select-none min-w-max">
                  <NavigationMenuLink className="w-auto">
                    Lenovo
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Dell
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">HP</NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    ASUS
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Acer
                  </NavigationMenuLink>
                  <NavigationMenuLink className="w-auto">
                    Case đồng bộ Dell
                  </NavigationMenuLink>
                </NavigationMenuContent>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </header>

        {children}

        <footer className="py-6 mt-4 border-t border-border">
          this is the footer
        </footer>
      </body>
    </html>
  );
}
